__default__:
  jobname: "{rule}_{wildcards}"
  nodes: 24
  ppn: 1
  pmem: "128000mb"
  walltime: "24:00:00"
  account: "ACCOUNT"
  queue: "cdb"
  email: "hpc@vort.org"
  mailon: "bea"
  jobout: "oe"
  outdir: "logs/pbs/"
