__default__:
  jobname: "{rule}-{wildcards}"
  nodes: 1
  ppn: 1
  pmem: "1000mb"
  walltime: "5:00"
  account: "ACCOUNT"
  queue: "cdb"
  email: "hpc@vort.org"
  mailon: "bea"
  jobout: "oe"
  outdir: "log/pbs/"
