__default__:
  jobname: "{rule}_{wildcards}"
  nodes: 1
  ncpus: 1
  mem: "16gb"
  walltime: "24:00:00"
  account: "ACCOUNT"
  queue: "APC"
  email: "hpc@vort.org"
  mailon: "bea"
  jobout: "oe"
  outdir: "logs/pbs/"
