__default__:
  jobname: "{rule}_{wildcards}"
  nodes: 1
  ppn: 1
  pmem: "64000mb"
  walltime: "2:00:00"
  account: "ACCOUNT"
  queue: "cdb"
  email: "hpc@vort.org"
  mailon: "bea"
  jobout: "oe"
  outdir: "log/pbs/"
