# input data
hmm_dir:          'data/hmms-enabled'
genome_batch_dir: 'data/genomes-enabled'

# e-value threshold for HMM search
evalue: 1.0e-2

# post-trimming aligned fraction threshold
aligned_fraction_threshold: 0.75

# threads to use when invoking multithreaded applications
threads: 1
ani_threads: 24

# cutoff thresholds for genome ANI clustering
ani_thresholds_min: 77   # minimum ANI cutoff
ani_thresholds_max: 99   # maximum ANI cutoff
ani_thresholds_n:   23   # number of ANI thresholds to consider
ani_min_aln:        5    # minumum number of bidirectional fragment mappings

# minimum number of links per cluster for tree correlation
min_cluster_links: 5

# degenerate tree threshold : exclude pairwise tree-to-tree
# comparisons where the ratio of non-unique leaf-to-leaf
# distances exceeds this threshold
degeneracy_threshold: 0.5
